spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ghr
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8090
logging:
  level:
    com:
      ghr:
        chat:
          dao:
            debug

chat:
  path: "http://localhost:8090/static"